### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [Pankajtanwarbanna/image-to-ascii-art#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by Pankajtanwarbanna** [comment]
Thanks for the heads up, @TechnologyClassroom ! I've added the LICENSE. Let me know if you are ok, closing this issue.

**Comment by TechnologyClassroom** [comment]
@Pankajtanwarbanna Nice!  There are technically two implementations of GPLv3.  There is [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html) and [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html).  GPL-3.0-or-later is better as it is compatible with future versions.  Which one would you prefer?

I could submit a pull request to add the license headers and LibreJS tags for the one you decide on.

**Comment by Pankajtanwarbanna** [comment]
As you suggested, We can go with [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html). Feel free to raise a PR. Thanks!

**Comment by TechnologyClassroom** [comment]
Nice!  Now anyone with LibreJS will be able to use the site.
